server:
  port: 8089

spring:
  # 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置Mysql
    url: jdbc:mysql://192.168.187.134:3306/zuel
    username: root
    password: 2null9
    driverClassName: com.mysql.jdbc.Driver
    # 初始化大小
    initialSize: 5
    # 最小值
    minIdle: 5
    # 最大值
    maxActive: 20
    # 等待超时时间 60s
    maxWait: 60000
    # 配置检测关闭空闲连接间隔时间  60s
    timeBetweenEvictionRunsMillis: 60000
    # 连接在连接池最小生存时间
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache, 并指定每个连接上的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 监控统计拦截的filter
    filters: stat,wall
    # 打开mergeSql功能, 慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #spring.datasource.useGlobalDataSourceStat=true

# Mybatis
mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: org.zuel.mould.bean
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl